CREATE TABLE IF NOT EXISTS `bug_reports` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `report_no` VARCHAR(32) NOT NULL,
    `username` VARCHAR(64) NOT NULL DEFAULT '',
    `account_id` VARCHAR(64) NOT NULL DEFAULT '',
    `account_name` VARCHAR(120) NOT NULL DEFAULT '',
    `category` VARCHAR(32) NOT NULL DEFAULT 'other',
    `severity` VARCHAR(16) NOT NULL DEFAULT 'medium',
    `title` VARCHAR(120) NOT NULL,
    `description` TEXT NOT NULL,
    `steps_to_reproduce` TEXT NULL,
    `expected_result` TEXT NULL,
    `actual_result` TEXT NULL,
    `contact` VARCHAR(255) NOT NULL DEFAULT '',
    `route` VARCHAR(255) NOT NULL DEFAULT '',
    `page_title` VARCHAR(255) NOT NULL DEFAULT '',
    `client_context` JSON DEFAULT NULL,
    `frontend_errors` JSON DEFAULT NULL,
    `system_logs_excerpt` JSON DEFAULT NULL,
    `runtime_logs_excerpt` JSON DEFAULT NULL,
    `account_logs_excerpt` JSON DEFAULT NULL,
    `server_context` JSON DEFAULT NULL,
    `mail_sent` TINYINT(1) NOT NULL DEFAULT 0,
    `mail_status` VARCHAR(32) NOT NULL DEFAULT '',
    `mail_message` VARCHAR(500) NOT NULL DEFAULT '',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `sent_at` TIMESTAMP NULL DEFAULT NULL,
    UNIQUE KEY `uk_bug_reports_report_no` (`report_no`),
    INDEX `idx_bug_reports_user_created` (`username`, `created_at`),
    INDEX `idx_bug_reports_account_created` (`account_id`, `created_at`),
    INDEX `idx_bug_reports_category_created` (`category`, `created_at`),
    INDEX `idx_bug_reports_mail_created` (`mail_sent`, `created_at`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'BUG/问题反馈留档表';
